class PostEntity {
  final String? postId;
  final String? title;
  final String? content;
  final String? createdAt;
  final String? clinicId;
  final ClinicEntity? clinic;
  final String? specieId;
  final SpecieEntityPost? specie;
  final int? numberOfComments;
  final List<PostMediaEntity>? postSocialMedia;
  final bool? autoGeneratedPost;
  final bool? sendCustomeMessageBefore;
  final int? userReactType;
  final int? petReactType;
  // New fields
  final int? reactHappyCount;
  final int? reactSadCount;
  final int? reactLoveCount;
  final int? reactAngryCount;
  final int? reactLikeCount;
  final int? reactNoneCount;
  final int? totalReactCount;
  final PetOwnerEntity? petOwner;
  final bool? petArereactedWithThisPost;
  final bool? userArereactedWithThisPost;

  const PostEntity({
    required this.postId,
    required this.title,
    required this.content,
    required this.createdAt,
    required this.clinicId,
    required this.clinic,
    required this.specieId,
    required this.specie,
    required this.numberOfComments,
    required this.postSocialMedia,
    required this.autoGeneratedPost,
    required this.sendCustomeMessageBefore,
    this.reactHappyCount,
    this.reactSadCount,
    this.userReactType,
    this.petReactType,
    this.reactLoveCount,
    this.reactAngryCount,
    this.reactLikeCount,
    this.reactNoneCount,
    this.totalReactCount,
    this.petOwner,
    this.petArereactedWithThisPost,
    this.userArereactedWithThisPost,
  });
}

class PostMediaEntity {
  final String? id;
  final String? imagePath;
  final String? videoPath;

  const PostMediaEntity({
    required this.id,
    required this.imagePath,
    required this.videoPath,
  });

  @override
  String toString() {
    return 'PostMediaEntity(id: $id, imagePath: $imagePath, videoPath: $videoPath)';
  }
}

class ClinicEntity {
  final String? name;
  final String? location;
  final String? city;
  final String? address;
  final String? phone;
  final dynamic code;
  final String? image;

  const ClinicEntity({
    required this.name,
    required this.location,
    required this.city,
    required this.address,
    required this.phone,
    required this.image,
    required this.code,
  });
}

class SpecieEntityPost {
  final String? arType;
  final String? enType;

  const SpecieEntityPost({required this.arType, required this.enType});
}

class PetOwnerEntity {
  final String? petName;
  final String? petId;
  final int? gender;
  final String? breedId;
  final String? specieId;
  final String? imageName;

  const PetOwnerEntity({
    required this.petName,
    required this.gender,
    required this.breedId,
    required this.petId,
    required this.specieId,
    required this.imageName,
  });
}

class MediaItem {
  final MediaType type;
  final String path;
  final String? id;
  final String? thumbnail;
  final String? duration;

  MediaItem({
    required this.type,
    required this.path,
    required this.id,
    required this.thumbnail,
    required this.duration,
  });

  bool get isImage => type == MediaType.image;
  bool get isVideo => type == MediaType.video;
}

enum MediaType { image, video }
