import '../../domain/entities/post_entity.dart';

class PostDataModel extends PostEntity {
  PostDataModel({
    required super.postId,
    required super.title,
    required super.content,
    required super.createdAt,
    required super.clinicId,
    required super.clinic,
    required super.specieId,
    required super.specie,
    required super.numberOfComments,
    required super.postSocialMedia,
    required super.autoGeneratedPost,
    required super.sendCustomeMessageBefore,
    super.reactHappyCount,
    super.reactSadCount,
    super.reactLoveCount,
    super.reactAngryCount,
    super.reactLikeCount,
    super.reactNoneCount,
    super.totalReactCount,
    super.petOwner,
    super.petArereactedWithThisPost,
    super.userArereactedWithThisPost,
    super.userReactType,
    super.petReactType,
  });

  factory PostDataModel.fromJson(Map<String, dynamic> json) {
    return PostDataModel(
      postId: json['id'],
      title: json['title'],
      content: json['content'],
      createdAt: json['createdAt'],
      userReactType: json['userReactType'],
      petReactType: json['petReactType'],
      clinicId: json['clinicId'],
      clinic: json['clinic'] != null ? ClinicModel.fromJson(json['clinic']) : null,
      specieId: json['specieId'],
      specie: json['speciePost'] != null ? SpecieModel.fromJson(json['speciePost']) : null,
      numberOfComments: json['numberOfComments'],
      postSocialMedia: json['postSocialMesdia'] != null
          ? List<PostMediaModel>.from(json['postSocialMesdia'].map((x) => PostMediaModel.fromJson(x)))
          : [],
      autoGeneratedPost: json['autoGeneratedPost'],
      sendCustomeMessageBefore: json['sendCustomeMessageBefore'],
      reactHappyCount: json['reactHappyCount'],
      reactSadCount: json['reactSadCount'],
      reactLoveCount: json['reactLoveCount'],
      reactAngryCount: json['reactAngryCount'],
      reactLikeCount: json['reactLikeCount'],
      reactNoneCount: json['reactNoneCount'],
      totalReactCount: json['totalReactCount'],
      petOwner: json['petOwner'] != null ? PetOwnerModel.fromJson(json['petOwner']) : null,
      petArereactedWithThisPost: json['petArereactedWithThisPost'],
      userArereactedWithThisPost: json['userArereactedWithThisPost'],
    );
  }
}

class PostMediaModel extends PostMediaEntity {
  PostMediaModel({required super.id, required super.imagePath, required super.videoPath});

  factory PostMediaModel.fromJson(Map<String, dynamic> json) {
    return PostMediaModel(
      id: json['id'],
      imagePath: json['imagePath'],
      videoPath: json['videoPath'],
    );
  }
}

class ClinicModel extends ClinicEntity {
  ClinicModel({
    required super.name,
    required super.location,
    required super.city,
    required super.address,
    required super.phone,
    required super.image,
    required super.code,
  });

  factory ClinicModel.fromJson(Map<String, dynamic> json) {
    return ClinicModel(
      name: json['name'],
      location: json['location'],
      city: json['city'],
      address: json['address'],
      phone: json['phone'],
      image: json['image'] ?? 'default.png',
      code: json['code'],
    );
  }
}

class SpecieModel extends SpecieEntityPost {
  SpecieModel({required super.arType, required super.enType});

  factory SpecieModel.fromJson(Map<String, dynamic> json) {
    return SpecieModel(
      arType: json['arType'],
      enType: json['enType'],
    );
  }
}

class PetOwnerModel extends PetOwnerEntity {
  PetOwnerModel({
    required super.petName,
    required super.gender,
    required super.petId,
    required super.breedId,
    required super.specieId,
    required super.imageName,
  });

  factory PetOwnerModel.fromJson(Map<String, dynamic> json) {
    return PetOwnerModel(
      petName: json['petName'],
      gender: json['gender'],
      breedId: json['breedId'],
      petId: json['id'],
      specieId: json['specieId'],
      imageName: json['imageName'],
    );
  }
}
