import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../../feeds/domain/entities/pet_mating_model.dart';

class PostsTab extends StatelessWidget {
  final PetMating pet;
  final bool isDarkMode;

  const PostsTab({
    super.key,
    required this.pet,
    required this.isDarkMode,
  });

  Widget _buildActionButton({
    required IconData icon,
    required String label,
    required Color color,
  }) {
    return Material(
      color: Colors.transparent,
      child: InkWell(
        onTap: () => HapticFeedback.lightImpact(),
        borderRadius: BorderRadius.circular(8),
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, size: 16, color: color),
              const SizedBox(width: 6),
              Text(
                label,
                style: TextStyle(
                  color: color,
                  fontSize: 12,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final autoGeneratedPosts = [
      {
        'title': '${pet.name} is looking for love!',
        'content': 'Ready to find the one! 💕 ${pet.name} is now open for love!',
        'timestamp': '2 hours ago',
        'reactions': 12,
        'comments': 3,
      },
      {
        'title': '${pet.name} completed profile!',
        'content': 'All set and ready to mingle! 🎉 ${pet.name} just completed their profile.',
        'timestamp': '1 day ago',
        'reactions': 8,
        'comments': 1,
      },
    ];

    return ListView.builder(
      physics: const BouncingScrollPhysics(),
      padding: const EdgeInsets.all(20),
      itemCount: autoGeneratedPosts.length,
      itemBuilder: (context, index) {
        final post = autoGeneratedPosts[index];
        return Container(
          margin: const EdgeInsets.only(bottom: 16),
          decoration: BoxDecoration(
            gradient: LinearGradient(
              colors: isDarkMode
                  ? [
                Colors.grey.shade800,
                Colors.grey.shade800,
              ]
                  : [
                Colors.white,
                Colors.grey.shade50,
              ],
            ),
            borderRadius: BorderRadius.circular(16),
            border: Border.all(
              color: isDarkMode
                  ? Colors.grey.shade700.withOpacity(0.5)
                  : Colors.grey.shade200,
            ),
            boxShadow: [
              BoxShadow(
                color: isDarkMode
                    ? Colors.black.withOpacity(0.2)
                    : Colors.black.withOpacity(0.05),
                blurRadius: 10,
                offset: const Offset(0, 4),
              ),
            ],
          ),
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Expanded(
                      child: Text(
                        post['title'] as String,
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                          color: isDarkMode ? Colors.white : Colors.black87,
                        ),
                      ),
                    ),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                      decoration: BoxDecoration(
                        color: isDarkMode
                            ? Colors.grey.shade700
                            : Colors.grey.shade100,
                        borderRadius: BorderRadius.circular(8),
                      ),
                      child: Text(
                        post['timestamp'] as String,
                        style: TextStyle(
                          color: isDarkMode ? Colors.grey.shade400 : Colors.grey.shade600,
                          fontSize: 12,
                        ),
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                Text(
                  post['content'] as String,
                  style: TextStyle(
                    color: isDarkMode ? Colors.grey.shade300 : Colors.grey.shade700,
                    height: 1.4,
                  ),
                ),
                const SizedBox(height: 16),
                Row(
                  children: [
                    _buildActionButton(
                      icon: Icons.favorite_border_rounded,
                      label: '${post['reactions']} reactions',
                      color: Colors.pink,
                    ),
                    const SizedBox(width: 20),
                    _buildActionButton(
                      icon: Icons.comment_outlined,
                      label: '${post['comments']} comments',
                      color: Colors.blue,
                    ),
                    const SizedBox(width: 20),
                    _buildActionButton(
                      icon: Icons.share_outlined,
                      label: 'Share',
                      color: Colors.green,
                    ),
                  ],
                ),
              ],
            ),
          ),
        );
      },
    );
  }
}